server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.253.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.253.128
ly:
  sms:
    accessKeyId: mdmy #你自己的acessKeyId
    accessKeySecret: mdmy #你自己的accessKeySecret
    signName: mdmy #签名名称
    verifyCodeTemplate: mdmy #模板名称

